### ISSUE TITLE
Don't put it on a new line, it pushes the content down causing misclicks

### ISSUE THREAD

**Issue by bfred-it** [musically-ut/github-forks-addon#6]
Perhaps it should try to be on the right of the title? I'm not sure of how it behaves when there are multiple forks

**Comment by musically-ut** [comment]
Thanks for creating the issue. I too had noticed the jump but wasn't sure whether it would be a nuisance or not. I guess it is.

I'll try play with having the extension load earlier (at document start instead of end) and having a placeholder to avoid the jump. If that seems sufficient, then I'll avoid having to replace a gazillion screenshots I have taken of the addon/extension in action. :)

**Comment by bfred-it** [comment]
hahah. Good idea! Perhaps have the placeholder added via CSS stylesheet (quick and light) and leave the JS at the end of the page (or the default position)

**Comment by bfred-it** [comment]
Also, I noticed that the style of your addon doesn't match the original "forked from" style, if that's what you were going for.

![GitHub "forked from" style](https://cloud.githubusercontent.com/assets/1402241/8359887/0b6f1348-1b1e-11e5-9b1d-48909263f227.png)
![Forks addon style](https://cloud.githubusercontent.com/assets/1402241/8359888/0b70819c-1b1e-11e5-91a0-d2d26a42e96b.png)

**Comment by musically-ut** [comment]
Good catch. Any suggestions as to how I should reframe the phrase "Notable fork"?

**Comment by bfred-it** [comment]
I'm working on a PR ;)

**Comment by bfred-it** [comment]
What do you think? 

![PR style](https://cloud.githubusercontent.com/assets/1402241/8360238/51cee460-1b20-11e5-9e4d-a223124abfa2.png)

Smaller star, gray, not a link, no parens (like it appears elsewhere), and "forked to" as opposed to "forked from"

**Comment by musically-ut** [comment]
:+1:

**Comment by musically-ut** [comment]
The effect of the jump is now somewhat diminished. Try out `0.3.0` and tell me if it can be improved further.

I have also included your new styling with this release (the update has been rolled out for both Firefox and Chrome).

I experimented for a while with an alternate placement as a button, but didn't get anywhere:

![](http://i.imgur.com/kIyk4co.png)
